const weatherQuotes = [
  {
    text: "And I never never ever do a thing about the weather for the weather never ever does a thing for me!",
    source: "Some sailor, probably",
    color: "#303288",
    minTemp: 20,
    maxTemp: 85,
  },
  {
    text: "Baby it's cold outside!",
    source: "Frank Loesser",
    color: '#116633',
    maxTemp: 31,
  },
  {
    text: "Wear a sweater!",
    source: "Mom",
    color: '#882244',
    minTemp: 35,
    maxTemp: 50,
    precipitation: false,
    maxWindSpeed: 10,
  },
  {
    text: "Don't forget your umbrella!",
    source: "Mom",
    color: '#882244',
    minTemp: 35,
    maxTemp: 45,
    condition: "Rain",
    maxWindSpeed: 22,
  },
  {
    text: "Wear your mittens!",
    source: "Mom",
    color: '#882244',
    maxTemp: 31,
  },
  {
    text: "Bundle up, or the cold wind will give you frostbite!",
    source: "Mom",
    color: '#882244',
    maxTemp: 31,
    minWindSpeed: 12,
  },
  {
    text: "Plan for double your usual travel time. Where there's snow, there's delays.",
    source: "Dad",
    color: '#334488',
    minTemp: -20,
    maxTemp: 40,
    condition: "Snow",
  },
  {
    text: "You might as well be walkin' on the sun",
    source: "Smash Mouth",
    color: '#dd8811',
    minTemp: 90,
    maxTemp: 120,
    condition: "clear",
    precipitation: false,
  },
  {
    text: "Man, it's a hot one, like seven inches from the midday sun",
    source: "Rob Thomas",
    color: '#992010',
    minTemp: 90,
    maxTemp: 120,
    precipitation: false,
  },
  {
    text: "Looks like good kite flying weather!",
    source: "Dad",
    color: '#334488',
    minTemp: 40,
    maxTemp: 90,
    precipitation: false,
    minWindSpeed: 10,
    maxWindSpeed: 30,
  },
  {
    text: "Some time outside would do you some good.",
    source: "Mom",
    color: '#882244',
    minTemp: 50,
    maxTemp: 80,
    precipitation: false,
    maxWindSpeed: 20,
  },
  {
    text: "Did you put on sunscreen?",
    source: "Mom",
    color: '#882244',
    minTemp: 65,
    condition: "Clear",
  },
  {
    text: "Who wants to go hiking?",
    source: "Dad",
    color: '#334488',
    minTemp: 45,
    maxTemp: 80,
    precipitation: false,
    maxWindSpeed: 30,
  },
  {
    text: "Don't track mud into the house!",
    source: "Mom",
    color: '#882244',
    condition: "Rain",
  },
];

const defaultWeatherQuote = {
  text: "Some weather we're having!",
  source: "Dad",
  color: '#334488',
};